### ISSUE TITLE
[REQUEST] Replace podcast icon with Amazon logo

### ISSUE THREAD

**Issue by WebSnke** [opensourcestories/opensourcestories.org#108]
The link to Amazon Music still uses the default podcast icon.
I suggest replacing it with the Amazon logo which is also available on [Font Awesome](https://fontawesome.com/icons/amazon?f=brands&s=solid).

![image](https://github.com/opensourcestories/opensourcestories.org/assets/94064167/c72926cc-1967-4f28-bd26-cd6056565ae9)

**Comment by clairecharles** [comment]
Hi I'd love to work on this :)

**Comment by clairecharles** [comment]
Hi @juliaferraioli I would like to know where the landing page is located so i can make changes :)

**Comment by juliaferraioli** [comment]
@clairecharles we keep our listings in a data file:

https://github.com/opensourcestories/opensourcestories.org/blob/main/data/podcasts.json

You can see that the Amazon one uses the generic `podcast.svg` file.

Those filenames correspond to the ones in:

https://github.com/opensourcestories/opensourcestories.org/tree/main/layouts/partials/svg

You'll want to add the Amazon svg (make sure to preserve the license in the SVG file like we have with the other ones) to that directory, then update the `podcasts.json` file.

That should be it! Let me know if you have questions.
