### ISSUE TITLE
Add Code of Conduct for StoryCorps project to site

### ISSUE THREAD

**Issue by amcasari** [opensourcestories/opensourcestories.org#21]
We need a Code of Conduct and moderation rules for StoryCorps project when people start submitting community conversations.

**Comment by juliaferraioli** [comment]
@amcasari on the code of conduct side, were you thinking that it would apply to the interviews and storycorps? Because I don't think we have any interactivity on the site that would necessitate it for site usage.

**Comment by amcasari** [comment]
Closing this because I can't remember where I was going with it.
