### ISSUE TITLE
[REQUEST] Add a favicon based on the logo

### ISSUE THREAD

**Issue by juliaferraioli** [opensourcestories/opensourcestories.org#36]
**Is your feature request related to a problem? Please describe.**
We should have a favicon!

**Describe the solution you'd like**
It should be based on our logo!

**Additional context**
We should handle light/dark mode, and preferably use an svg instead of an ico.

I cannot attach the svg to the issue, but it is located [in source](https://github.com/opensourcestories/opensourcestories.org/blob/main/static/images/logos/logo.svg). Other acceptable colors for the logo are: #29503c or #ffffff.

**Comment by npkeerthi** [comment]
> **Is your feature request related to a problem? Please describe.** We should have a favicon!
> 
> **Describe the solution you'd like** It should be based on our logo!
> 
> **Additional context** We should handle light/dark mode, and preferably use an svg instead of an ico.
> 
> I cannot attach the svg to the issue, but it is located [in source](https://github.com/opensourcestories/opensourcestories.org/blob/main/static/images/logos/logo.svg). Other acceptable colors for the logo are: #29503c or #ffffff.

Hey can I work on it ? or did it solved?

**Comment by juliaferraioli** [comment]
You can absolutely work on it, thank you @npkeerthi! I've assigned the issue to you. I'll give you some feedback in your PR.

**Comment by npkeerthi** [comment]
@juliaferraioli Hey I have added a Favicon to your project check it
