### ISSUE TITLE
Typo on about page

### ISSUE THREAD

**Issue by Arthur-Milchior** [opensourcestories/opensourcestories.org#39]
On https://www.opensourcestories.org/about/ for some reason "amanda casari is a researcher" misses upper cases on the initial.

Also, I was not able to find a way to make a PR, as this text does not seems to be in the about page on this repo

**Comment by juliaferraioli** [comment]
The casing is intentional, but thanks for checking! We're making use of data templates, so you can see the data file [here](https://github.com/opensourcestories/opensourcestories.org/blob/main/data/contributors.json).

**Comment by Arthur-Milchior** [comment]
Then you may be interested in knowing that in https://www.opensourcestories.org/about/ the first sentence upper case in a standard way the name of amanda casari. (I actually searched other occurrence of the name before making the issue in order to check whether there is a consistent rule here)

**Comment by juliaferraioli** [comment]
Oh, good catch! @amcasari, would you like the about page to be lower case?

Also, let us see if the @all-contributors bot can add @Arthur-Milchior for content.

**Comment by amcasari** [comment]
Thanks for catching this! I haven't been strict about formatting. I do prefer lowercase, when possible.
