### ISSUE TITLE
Create a containerized development environment for the site

### ISSUE THREAD

**Issue by juliaferraioli** [opensourcestories/opensourcestories.org#68]
[Development containers](https://code.visualstudio.com/docs/remote/containers) can help new or potential contributors get an environment up and running with less effort. There's even [one specifically for Hugo sites](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/hugo)!

It would be excellent to get one set up for [opensourcestories.org](https://opensourcestories.org).

**Comment by LuvvAggarwal** [comment]
Is someone working on it?

**Comment by juliaferraioli** [comment]
As you can see, @tylerauerbeck started a PR, but I think didn't have time to make the requested changes. If you want to take a stab at it, go ahead!

**Comment by juliaferraioli** [comment]
Closed by #97
